
   COMMENT ON COLUMN "EBA_CUST_CONTACT_TYPES"."ID" IS 'Primary Key, never changes.  Automatically generated by Oracle Database';
   COMMENT ON COLUMN "EBA_CUST_CONTACT_TYPES"."CONTACT_TYPE" IS 'The name for the Contact type.';
   COMMENT ON COLUMN "EBA_CUST_CONTACT_TYPES"."IS_ACTIVE" IS 'Used to Enable or Disable a Contact types from being used in the transaction.';
   COMMENT ON COLUMN "EBA_CUST_CONTACT_TYPES"."CREATED" IS 'The date on which the record is created, automatically updated.';
   COMMENT ON COLUMN "EBA_CUST_CONTACT_TYPES"."CREATED_BY" IS 'The user who created the record, automatically updated.';
   COMMENT ON COLUMN "EBA_CUST_CONTACT_TYPES"."UPDATED" IS 'The date on which the record is last updated, automatically updated.';
   COMMENT ON COLUMN "EBA_CUST_CONTACT_TYPES"."UPDATED_BY" IS 'The user who last updated the record, automatically updated.';
   COMMENT ON TABLE "EBA_CUST_CONTACT_TYPES"  IS 'Stores information about various type of contacts.';