  CREATE TABLE "%USER_NAME%"."EBA_CUST_FEEDBACK" 
   (	"ID" NUMBER CONSTRAINT "EBA_CUST_FEEDBACK_PK" NOT NULL ENABLE,
	"APPLICATION_ID" NUMBER NOT NULL ENABLE,
	"PAGE_ID" NUMBER NOT NULL ENABLE,
	"FEEDBACK" VARCHAR2(4000),
	"RESPONSE" VARCHAR2(4000),
	"TYPE_ID" NUMBER,
	"STATUS" VARCHAR2(30),
	"CREATED" TIMESTAMP (6) WITH TIME ZONE,
	"CREATED_BY" VARCHAR2(255),
	"UPDATED" TIMESTAMP (6) WITH TIME ZONE,
	"UPDATED_BY" VARCHAR2(255),
	PRIMARY KEY ("ID")
  USING INDEX
  PCTFREE 10 INITRANS 20 MAXTRANS 255 LOGGING
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  TABLESPACE "DATA"