  CREATE TABLE "%USER_NAME%"."EBA_CUST_VERIFICATIONS" 
   (	"ID" NUMBER,
	"CUST_ID" NUMBER,
	"VERIFIED_BY" VARCHAR2(255) NOT NULL ENABLE,
	"VERIFICATION_COMMENT" VARCHAR2(4000),
	"CREATED" TIMESTAMP (6) WITH TIME ZONE,
	"CREATED_BY" VARCHAR2(255),
	"UPDATED" TIMESTAMP (6) WITH TIME ZONE,
	"UPDATED_BY" VARCHAR2(255),
	PRIMARY KEY ("ID")
  USING INDEX
  PCTFREE 10 INITRANS 20 MAXTRANS 255 LOGGING
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  TABLESPACE "DATA"