  CREATE TABLE "%USER_NAME%"."EBA_CUST_ERRORS" 
   (	"ID" NUMBER NOT NULL ENABLE,
	"ERR_TIME" TIMESTAMP (6) WITH TIME ZONE DEFAULT current_timestamp NOT NULL ENABLE,
	"APP_ID" NUMBER,
	"APP_PAGE_ID" NUMBER,
	"APP_USER" VARCHAR2(512),
	"USER_AGENT" VARCHAR2(4000),
	"IP_ADDRESS" VARCHAR2(512),
	"IP_ADDRESS2" VARCHAR2(512),
	"MESSAGE" VARCHAR2(4000),
	"PAGE_ITEM_NAME" VARCHAR2(255),
	"REGION_ID" NUMBER,
	"COLUMN_ALIAS" VARCHAR2(255),
	"ROW_NUM" NUMBER,
	"APEX_ERROR_CODE" VARCHAR2(255),
	"ORA_SQLCODE" NUMBER,
	"ORA_SQLERRM" VARCHAR2(4000),
	"ERROR_BACKTRACE" VARCHAR2(4000),
	CONSTRAINT "EBA_CUST_ERRORS_PK" PRIMARY KEY ("ID")
  USING INDEX
  PCTFREE 10 INITRANS 20 MAXTRANS 255 LOGGING
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  TABLESPACE "DATA"