  CREATE UNIQUE INDEX "%USER_NAME%"."EBA_CUST_ERROR_LOOKUP_UK" ON "%USER_NAME%"."EBA_CUST_ERROR_LOOKUP" ("CONSTRAINT_NAME","LANGUAGE_CODE")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 