
   COMMENT ON COLUMN "EBA_CUST_CATEGORIES"."ID" IS 'Primary Key, never changes.  Automatically generated by Oracle Database';
   COMMENT ON COLUMN "EBA_CUST_CATEGORIES"."CATEGORY" IS 'The unique name for the Category.';
   COMMENT ON COLUMN "EBA_CUST_CATEGORIES"."DESCRIPTION" IS 'A brief description about the Category.';
   COMMENT ON COLUMN "EBA_CUST_CATEGORIES"."IS_ACTIVE" IS 'Used to Enable or Disable a Category from being used in the transaction.';
   COMMENT ON COLUMN "EBA_CUST_CATEGORIES"."CREATED" IS 'The date on which the record is created, automatically updated.';
   COMMENT ON COLUMN "EBA_CUST_CATEGORIES"."CREATED_BY" IS 'The user who created the record, automatically updated.';
   COMMENT ON COLUMN "EBA_CUST_CATEGORIES"."UPDATED" IS 'The date on which the record is last updated, automatically updated.';
   COMMENT ON COLUMN "EBA_CUST_CATEGORIES"."UPDATED_BY" IS 'The user who last updated the record, automatically updated.';
   COMMENT ON TABLE "EBA_CUST_CATEGORIES"  IS 'Stores Category information.';