
   COMMENT ON COLUMN "EBA_CUST_ADMINISTRATORS"."ID" IS 'Primary Key, never changes.  Automatically generated by Oracle Database';
   COMMENT ON COLUMN "EBA_CUST_ADMINISTRATORS"."APP_USER" IS 'The login name of user who have administration rights.';
   COMMENT ON COLUMN "EBA_CUST_ADMINISTRATORS"."CREATED" IS 'The date on which the record is created, automatically updated.';
   COMMENT ON COLUMN "EBA_CUST_ADMINISTRATORS"."CREATED_BY" IS 'The user who created the record, automatically updated.';
   COMMENT ON COLUMN "EBA_CUST_ADMINISTRATORS"."UPDATED" IS 'The date on which the record is last updated, automatically updated.';
   COMMENT ON COLUMN "EBA_CUST_ADMINISTRATORS"."UPDATED_BY" IS 'The user who last updated the record, automatically updated.';
   COMMENT ON TABLE "EBA_CUST_ADMINISTRATORS"  IS 'Stores the login name who have administration rights.';