  CREATE TABLE "%USER_NAME%"."EBA_CUST_EMAIL_LOG" 
   (	"ID" NUMBER,
	"ROW_VERSION_NUMBER" NUMBER,
	"EMAIL_FIRST_TO" VARCHAR2(255),
	"EMAIL_TO" VARCHAR2(4000),
	"EMAIL_FROM" VARCHAR2(255),
	"BODY_SIZE" NUMBER,
	"CUSTOMER_ID" NUMBER,
	"EMAIL_TYPE" VARCHAR2(30),
	"CREATED" TIMESTAMP (6) WITH TIME ZONE,
	"CREATED_BY" VARCHAR2(255),
	"UPDATED" TIMESTAMP (6) WITH TIME ZONE,
	"UPDATED_BY" VARCHAR2(255),
	PRIMARY KEY ("ID")
  USING INDEX
  PCTFREE 10 INITRANS 20 MAXTRANS 255 LOGGING
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  TABLESPACE "DATA"