
   COMMENT ON COLUMN "EBA_CUST_VIEWS_LOG"."ID" IS 'Primary Key, never changes.  Automatically generated by Oracle Database';
   COMMENT ON COLUMN "EBA_CUST_VIEWS_LOG"."TABLE_PRIMARY_ID" IS 'The primary key value of Customer or Contact table.';
   COMMENT ON COLUMN "EBA_CUST_VIEWS_LOG"."VIEW_TYPE" IS 'The type of view, either "CUS" - Customer or "CON" - Contact.';
   COMMENT ON COLUMN "EBA_CUST_VIEWS_LOG"."VIEW_COUNT" IS 'Total number of times the Customer details or Contact details been viewed.';
   COMMENT ON TABLE "EBA_CUST_VIEWS_LOG"  IS 'Stores the count of Customer & Contacts being viewed.';