  CREATE TABLE "%USER_NAME%"."EBA_CUST_ISSUES" 
   (	"ID" NUMBER,
	"CUSTOMER_ID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(255) NOT NULL ENABLE,
	"ISSUE_TYPE" VARCHAR2(10) NOT NULL ENABLE,
	"STATUS_ID" NUMBER NOT NULL ENABLE,
	"PRODUCT_ID" NUMBER,
	"DETAILS" VARCHAR2(4000),
	"RESOLUTION" VARCHAR2(4000),
	"CREATED" TIMESTAMP (6) WITH TIME ZONE,
	"CREATED_BY" VARCHAR2(255),
	"UPDATED" TIMESTAMP (6) WITH TIME ZONE,
	"UPDATED_BY" VARCHAR2(255),
	PRIMARY KEY ("ID")
  USING INDEX
  PCTFREE 10 INITRANS 20 MAXTRANS 255 LOGGING
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  TABLESPACE "DATA"