
   COMMENT ON COLUMN "EBA_CUST_LINKS"."ID" IS 'Primary Key, never changes.  Automatically generated by Oracle Database';
   COMMENT ON COLUMN "EBA_CUST_LINKS"."CUSTOMER_ID" IS 'The ID of the Customer, the value is referred from ID field in eba_cust_customers.';
   COMMENT ON COLUMN "EBA_CUST_LINKS"."CONTACT_ID" IS 'The ID of the Contact, the value is referred from ID field in eba_cust_contacts.';
   COMMENT ON COLUMN "EBA_CUST_LINKS"."LINK" IS 'The link which points to the additional data.';
   COMMENT ON COLUMN "EBA_CUST_LINKS"."LINK_TYPE" IS 'The type of link.';
   COMMENT ON COLUMN "EBA_CUST_LINKS"."CREATED" IS 'The date on which the record is created, automatically updated.';
   COMMENT ON COLUMN "EBA_CUST_LINKS"."CREATED_BY" IS 'The user who created the record, automatically updated.';
   COMMENT ON COLUMN "EBA_CUST_LINKS"."UPDATED" IS 'The date on which the record is last updated, automatically updated.';
   COMMENT ON COLUMN "EBA_CUST_LINKS"."UPDATED_BY" IS 'The user who last updated the record, automatically updated.';
   COMMENT ON TABLE "EBA_CUST_LINKS"  IS 'Stores various Links pointing to the Contacts.';