  CREATE TABLE "%USER_NAME%"."EBA_CUST_ACCESS_LEVELS" 
   (	"ID" NUMBER NOT NULL ENABLE,
	"ACCESS_LEVEL" VARCHAR2(30) NOT NULL ENABLE,
	"ROW_VERSION" NUMBER,
	CONSTRAINT "EBA_CUST_ACC_LVL_ACC_LVL_CK" CHECK (access_level in (
                                                    'Administrator',
                                                    'Contributor',
                                                    'Reader' )) ENABLE,
	CONSTRAINT "EBA_CUST_ACCESS_LEVELS_PK" PRIMARY KEY ("ID")
  USING INDEX
  PCTFREE 10 INITRANS 20 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"