  CREATE TABLE "%USER_NAME%"."EBA_CUST_COUNTRIES" 
   (	"ID" NUMBER,
	"COUNTRY_CODE" VARCHAR2(30) NOT NULL ENABLE,
	"COUNTRY_NAME" VARCHAR2(255) NOT NULL ENABLE,
	"REGION_ID" NUMBER,
	"DISPLAY_YN" VARCHAR2(1),
	"ROW_VERSION_NUMBER" NUMBER,
	"CREATED" TIMESTAMP (6) WITH TIME ZONE,
	"CREATED_BY" VARCHAR2(255),
	"UPDATED" TIMESTAMP (6) WITH TIME ZONE,
	"UPDATED_BY" VARCHAR2(255),
	CONSTRAINT "EBA_CUST_COUNTRIES_DISP_CC" CHECK (display_yn in ('Y','N')) ENABLE,
	PRIMARY KEY ("ID")
  USING INDEX
  PCTFREE 10 INITRANS 20 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"