  CREATE TABLE "%USER_NAME%"."EBA_CUST_NOTIFICATIONS" 
   (	"ID" NUMBER NOT NULL ENABLE,
	"ROW_VERSION_NUMBER" NUMBER,
	"NOTIFICATION_NAME" VARCHAR2(255) NOT NULL ENABLE,
	"NOTIFICATION_DESCRIPTION" VARCHAR2(4000),
	"NOTIFICATION_TYPE" VARCHAR2(30) NOT NULL ENABLE,
	"DISPLAY_SEQUENCE" NUMBER,
	"DISPLAY_FROM" TIMESTAMP (6) WITH TIME ZONE,
	"DISPLAY_UNTIL" TIMESTAMP (6) WITH TIME ZONE,
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH TIME ZONE,
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE,
	"UPDATED" TIMESTAMP (6) WITH TIME ZONE,
	CONSTRAINT "EBA_CUST_NOTIF_TP_CC" CHECK (notification_type in ('RED','YELLOW')) ENABLE,
	CONSTRAINT "EBA_CUST_NOTIF_PK" PRIMARY KEY ("ID")
  USING INDEX
  PCTFREE 10 INITRANS 20 MAXTRANS 255 LOGGING
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  TABLESPACE "DATA"