  CREATE TABLE "%USER_NAME%"."EBA_CUST_USERS" 
   (	"ID" NUMBER NOT NULL ENABLE,
	"USERNAME" VARCHAR2(255) NOT NULL ENABLE,
	"ACCESS_LEVEL_ID" NUMBER NOT NULL ENABLE,
	"ACCOUNT_LOCKED" VARCHAR2(1) NOT NULL ENABLE,
	"ROW_VERSION" NUMBER,
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH TIME ZONE,
	"UPDATED_BY" VARCHAR2(255),
	"UPDATED" TIMESTAMP (6) WITH TIME ZONE,
	CONSTRAINT "EBA_CUST_USERS_USERNAME_CK" CHECK (upper(username)=username) ENABLE,
	CONSTRAINT "EBA_CUST_USERS_ACC_LOCKED_CK" CHECK (account_locked in ('Y','N')) ENABLE,
	CONSTRAINT "EBA_CUST_USERS_PK" PRIMARY KEY ("ID")
  USING INDEX
  PCTFREE 10 INITRANS 20 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"