  CREATE TABLE "%USER_NAME%"."EBA_CUST_PREFERENCES" 
   (	"ID" NUMBER NOT NULL ENABLE,
	"PREFERENCE_NAME" VARCHAR2(255) NOT NULL ENABLE,
	"PREFERENCE_VALUE" VARCHAR2(255),
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE,
	"CREATED_ON" TIMESTAMP (6) WITH TIME ZONE,
	"UPDATED_BY" VARCHAR2(255),
	"UPDATED_ON" TIMESTAMP (6) WITH TIME ZONE,
	CONSTRAINT "EBA_CUST_PREFS_PREFNAME_CK" CHECK (upper(preference_name)=preference_name) ENABLE,
	CONSTRAINT "EBA_CUST_PREFERENCES_PK" PRIMARY KEY ("ID")
  USING INDEX
  PCTFREE 10 INITRANS 20 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"