  CREATE TABLE "%USER_NAME%"."EBA_CUST_CUSTOMERS" 
   (	"ID" NUMBER NOT NULL ENABLE,
	"PARENT_CUSTOMER_ID" NUMBER,
	"ROW_VERSION_NUMBER" NUMBER NOT NULL ENABLE,
	"ROW_KEY" VARCHAR2(60) NOT NULL ENABLE,
	"CUSTOMER_NAME" VARCHAR2(255) NOT NULL ENABLE,
	"CUSTOMER_NAME_UPPER" VARCHAR2(255) NOT NULL ENABLE,
	"CUSTOMER_ACCOUNT_NUMBER" VARCHAR2(255),
	"INDUSTRY_ID" NUMBER,
	"CATEGORY_ID" NUMBER,
	"STATUS_ID" NUMBER,
	"TYPE_ID" NUMBER,
	"USE_CASE_ID" NUMBER,
	"GEOGRAPHY_ID" NUMBER,
	"COUNTRY_ID" NUMBER,
	"DEFAULT_TIMEZONE" VARCHAR2(255),
	"REFERENCABLE" VARCHAR2(30),
	"MARQUEE_CUSTOMER_YN" VARCHAR2(1),
	"REFERENCE_PHASE_ID" NUMBER,
	"REF_RECRUITMENT_OWNER" VARCHAR2(255),
	"STRATEGIC_CUSTOMER_PROGRAM_YN" VARCHAR2(1) DEFAULT 'N',
	"TAGS" VARCHAR2(4000),
	"SALES_CHANNEL_ID" NUMBER,
	"CUSTOMER_PRODUCTS" VARCHAR2(4000),
	"NUMBER_OF_USERS" VARCHAR2(60),
	"SUMMARY" VARCHAR2(4000),
	"CUSTOMER_PROFILE" CLOB,
	"APPLICATIONS" CLOB,
	"LOGO_BLOB" BLOB,
	"LOGO_NAME" VARCHAR2(512),
	"LOGO_MIMETYPE" VARCHAR2(512),
	"LOGO_CHARSET" VARCHAR2(512),
	"LOGO_LASTUPD" DATE,
	"WEB_SITE" VARCHAR2(1000),
	"LINKEDIN" VARCHAR2(1000),
	"FACEBOOK" VARCHAR2(1000),
	"TWITTER" VARCHAR2(1000),
	"STOCK_SYMBOL" VARCHAR2(30),
	"TOTAL_CONTRACT_VALUE" NUMBER,
	"ANNUAL_RECURRING_REVENUE" NUMBER,
	"CURRENCY" VARCHAR2(20),
	"DISCOUNT_LEVEL" NUMBER,
	"SIC" VARCHAR2(30),
	"DUNS" VARCHAR2(30),
	"SUPPORT_ID" VARCHAR2(50),
	"PARTY_ID" VARCHAR2(50),
	"PARENT_PARTY_ID" VARCHAR2(50),
	"PARTY_NAME" VARCHAR2(255),
	"PARTENT_PARTY_NAME" VARCHAR2(255),
	"CREATED" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE,
	"UPDATED" TIMESTAMP (6) WITH TIME ZONE,
	"UPDATED_BY" VARCHAR2(255),
	CONSTRAINT "EBA_CUST_CUSTOMERS_PK" PRIMARY KEY ("ID")
  USING INDEX
  PCTFREE 10 INITRANS 20 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE,
	CONSTRAINT "EBA_CUST_CUSTOMERS_UK" UNIQUE ("CUSTOMER_NAME")
  USING INDEX
  PCTFREE 10 INITRANS 20 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"
 LOB ("CUSTOMER_PROFILE") STORE AS SECUREFILE  (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING NOCOMPRESS KEEP_DUPLICATES 
  STORAGE( INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))
 LOB ("APPLICATIONS") STORE AS SECUREFILE  (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING NOCOMPRESS KEEP_DUPLICATES 
  STORAGE( INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))
 LOB ("LOGO_BLOB") STORE AS SECUREFILE  (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING NOCOMPRESS KEEP_DUPLICATES 
  STORAGE( INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))