  CREATE TABLE "%USER_NAME%"."EBA_CUST_HISTORY" 
   (	"ID" NUMBER,
	"ROW_VERSION_NUMBER" NUMBER,
	"TABLE_NAME" VARCHAR2(255),
	"COMPONENT_ID" NUMBER,
	"COMPONENT_ROWKEY" VARCHAR2(30),
	"COLUMN_NAME" VARCHAR2(60) NOT NULL ENABLE,
	"OLD_VALUE" VARCHAR2(4000),
	"NEW_VALUE" VARCHAR2(4000),
	"CHANGE_DATE" TIMESTAMP (6) WITH TIME ZONE,
	"CHANGED_BY" VARCHAR2(255),
	CONSTRAINT "EBA_CUST_HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX
  PCTFREE 10 INITRANS 20 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"